CREATE DATABASE IF NOT EXISTS cadastro;

USE cadastro;

CREATE TABLE tab_clientes(
	id integer auto_increment primary key,
	nome varchar(100),
	pai varchar(100),
	mae varchar(100),
	rua varchar(100),
	complemento varchar(100),
	numero varchar(20),
	cep varchar(20),
	bairro varchar(20),
	cidade varchar(100),
	matricula varchar(20),
	cpf varchar(20),
	identidade varchar(20),
	titulo varchar(20),
	zona varchar(20),
	secao varchar(20),
	pis varchar(20),
	reservista varchar(20),
	escolar varchar(50),
	instituicao varchar(50),
	curso varchar(50),
	deficiente varchar(50),
	nota varchar(100), 
	cargo varchar(100),
	funcao varchar(50),
	forma_admissao varchar(20),
	regime varchar(10),
	setor varchar(50),
	carteiratrabalho varchar(20),
	email varchar(50),
	telefone varchar(20),
	celular varchar(20),
	whatsapp varchar(20),
	data_nascimento date,
	data_admissao date,
	sexo varchar(10),
	nacionalidade varchar(42),
	naturalidade varchar(20),
	estado varchar(20),
	estado_civil varchar(10),
	numero_dependente int(20),
	banco varchar(50),
	agencia varchar(20),
	conta_corrente varchar(20),
	status varchar(10),
    foto varchar(200),
	data_cadastro DATETIME DEFAULT CURRENT_TIMESTAMP,
	data_alteracao timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
